services:
  # ไม่ใช้ local DB container เพราะใช้ external PostgreSQL ที่ 192.168.2.50

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: it-request-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-staging}
      - PORT=3001
      - PGHOST=192.168.2.50
      - PGUSER=${PGUSER:-it_admin}
      - PGPASSWORD=${PGPASSWORD:-it_password}
      - PGDATABASE=${PGDATABASE:-it_request_db}
      - PGPORT=5432
    volumes:
      - ./backend/uploads:/app/uploads
    extra_hosts:
      - "db:192.168.2.50"
    restart: unless-stopped

networks:
  it-network:
    driver: bridge
