version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: it-request-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - PGHOST=db
      - PGUSER=it_admin
      - PGPASSWORD=it_password
      - PGDATABASE=it_request_db
      - PGPORT=5432
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db


